import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Providers } from "./provider";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vipin Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={"h-[60px"}>
        <header>
          <nav>
            <Nav />
          </nav>
        </header>
        <main className="mt-[60px]">
          <Providers>{children}</Providers>
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
